# Generated by Django 4.2.7 on 2025-04-13 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='body_type',
            field=models.CharField(choices=[('sedan', 'Седан'), ('hatchback', 'Хэтчбек'), ('SUV', 'Внедорожник'), ('wagon', 'Универсал'), ('minivan', 'Минивэн'), ('pickup', 'Пикап'), ('coupe', 'Купе'), ('cabrio', 'Кабриолет')], default='Внедорожник', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='drive_unit',
            field=models.CharField(choices=[('rear', 'Задний'), ('front', 'Передний'), ('full', 'Полный')], default='Полный', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('gasoline', 'Бензин'), ('diesel', 'Дизель'), ('hybrid', 'Гибрид'), ('electro', 'Электро')], default='Дизель', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='gearbox',
            field=models.CharField(choices=[('manual', 'Механика'), ('automatic', 'Автомат'), ('вариатор', 'CVT'), ('robot', 'Робот')], default='Автомат', max_length=20),
            preserve_default=False,
        ),
    ]
